app = "libsql-proxy"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3000"

[[mounts]]
source = "libsql_data"
destination = "/app/data"

[[services]]
internal_port = 3000
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[metrics]
port = 9091
path = "/metrics"
